TG_ID_COLUMN = "Telegram ID"
ROLE_COLUMN = "Role"
MANAGER_IDS_COLUMN = "ManagerIDs"

TASK_ID_COLUMN = "TaskId"
EMPLOYEE_ID_COLUMN = "EmployeeID"
DEADLINE_COLUMN = "Deadline"
UPDATED_AT_COLUMN = "UpdatedAt"

TITLE_COLUMN = "Title"
DESCRIPTION_COLUMN = "Description"
LEAD_ID_COLUMN = "LeadID"
AUTHOR_ID_COLUMN = "AuthorID"
STATUS_COLUMN = "Status"
CREATED_AT_COLUMN = "CreatedAt"

STARTED_AT_COLUMN = "StartedAt"
<<<<<<< Updated upstream
ENDED_AT_COLUMN = "EndedAt"
=======
ENDED_AT_COLUMN = "EndedAt"

BIND_REQUEST_ID_COLUMN = "RequestID"
BIND_EMPLOYEE_ID_COLUMN = "EmployeeID"
BIND_EMPLOYEE_ROLE_COLUMN = "EmployeeRole"
BIND_LEAD_ID_COLUMN = "LeadID"
BIND_CREATED_AT_COLUMN = "CreatedAt"
NOTIFICATION_MORNING_TIME_COLUMN = "NotificationMorningTime"
NOTIFICATION_EVENING_TIME_COLUMN = "NotificationEveningTime"
NOTIFICATION_TIMEZONE_COLUMN = "NotificationTimezone"
>>>>>>> Stashed changes
